import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/provider/redux/ReduxProvider";
import "./globals.css";
import AnonProvider from "@/provider/anon/anonprovider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
    <html lang="en">
    <body className={inter.className}><AnonProvider>{children}</AnonProvider></body>
    </html>
    </ReduxProvider>
  );
}
